# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from material_app.grpc import material_app_pb2 as material__app_dot_grpc_dot_material__app__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in material_app/grpc/material_app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EquipmentCategoryControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/material_service.material_app.EquipmentCategoryController/Create',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/material_service.material_app.EquipmentCategoryController/Destroy',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/material_service.material_app.EquipmentCategoryController/List',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryListRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/material_service.material_app.EquipmentCategoryController/PartialUpdate',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryPartialUpdateRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/material_service.material_app.EquipmentCategoryController/Retrieve',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRetrieveRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/material_service.material_app.EquipmentCategoryController/Update',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
                _registered_method=True)


class EquipmentCategoryControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EquipmentCategoryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryListRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryPartialUpdateRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRetrieveRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'material_service.material_app.EquipmentCategoryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('material_service.material_app.EquipmentCategoryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EquipmentCategoryController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentCategoryController/Create',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentCategoryController/Destroy',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentCategoryController/List',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryListRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentCategoryController/PartialUpdate',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryPartialUpdateRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentCategoryController/Retrieve',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRetrieveRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentCategoryController/Update',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EquipmentControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/material_service.material_app.EquipmentController/Create',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/material_service.material_app.EquipmentController/Destroy',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/material_service.material_app.EquipmentController/List',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentListRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/material_service.material_app.EquipmentController/PartialUpdate',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentPartialUpdateRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/material_service.material_app.EquipmentController/Retrieve',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentRetrieveRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/material_service.material_app.EquipmentController/Update',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
                _registered_method=True)


class EquipmentControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EquipmentControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentListRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentPartialUpdateRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentRetrieveRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'material_service.material_app.EquipmentController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('material_service.material_app.EquipmentController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EquipmentController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentController/Create',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentController/Destroy',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentController/List',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentListRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentController/PartialUpdate',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentPartialUpdateRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentController/Retrieve',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentRetrieveRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentController/Update',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EquipmentMovementControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/material_service.material_app.EquipmentMovementController/Create',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/material_service.material_app.EquipmentMovementController/Destroy',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/material_service.material_app.EquipmentMovementController/List',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementListRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/material_service.material_app.EquipmentMovementController/PartialUpdate',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementPartialUpdateRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/material_service.material_app.EquipmentMovementController/Retrieve',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRetrieveRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/material_service.material_app.EquipmentMovementController/Update',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
                _registered_method=True)


class EquipmentMovementControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EquipmentMovementControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementListRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementPartialUpdateRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRetrieveRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'material_service.material_app.EquipmentMovementController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('material_service.material_app.EquipmentMovementController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EquipmentMovementController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentMovementController/Create',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentMovementController/Destroy',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentMovementController/List',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementListRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentMovementController/PartialUpdate',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementPartialUpdateRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentMovementController/Retrieve',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRetrieveRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.EquipmentMovementController/Update',
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.EquipmentMovementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MaintenanceLogControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/material_service.material_app.MaintenanceLogController/Create',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/material_service.material_app.MaintenanceLogController/Destroy',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/material_service.material_app.MaintenanceLogController/List',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogListRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/material_service.material_app.MaintenanceLogController/PartialUpdate',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogPartialUpdateRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/material_service.material_app.MaintenanceLogController/Retrieve',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRetrieveRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/material_service.material_app.MaintenanceLogController/Update',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
                _registered_method=True)


class MaintenanceLogControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaintenanceLogControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogListRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogPartialUpdateRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRetrieveRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'material_service.material_app.MaintenanceLogController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('material_service.material_app.MaintenanceLogController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaintenanceLogController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenanceLogController/Create',
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenanceLogController/Destroy',
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenanceLogController/List',
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogListRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenanceLogController/PartialUpdate',
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogPartialUpdateRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenanceLogController/Retrieve',
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRetrieveRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenanceLogController/Update',
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenanceLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MaintenancePlanControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/material_service.material_app.MaintenancePlanController/Create',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/material_service.material_app.MaintenancePlanController/Destroy',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/material_service.material_app.MaintenancePlanController/List',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanListRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/material_service.material_app.MaintenancePlanController/PartialUpdate',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanPartialUpdateRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/material_service.material_app.MaintenancePlanController/Retrieve',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRetrieveRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/material_service.material_app.MaintenancePlanController/Update',
                request_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRequest.SerializeToString,
                response_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
                _registered_method=True)


class MaintenancePlanControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaintenancePlanControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanListRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanPartialUpdateRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRetrieveRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRequest.FromString,
                    response_serializer=material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'material_service.material_app.MaintenancePlanController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('material_service.material_app.MaintenancePlanController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaintenancePlanController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenancePlanController/Create',
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenancePlanController/Destroy',
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenancePlanController/List',
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanListRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenancePlanController/PartialUpdate',
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanPartialUpdateRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenancePlanController/Retrieve',
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRetrieveRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/material_service.material_app.MaintenancePlanController/Update',
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanRequest.SerializeToString,
            material__app_dot_grpc_dot_material__app__pb2.MaintenancePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
