# Generated by Django 5.2.3 on 2025-06-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la fourniture')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité de mesure')),
                ('prix_achat_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat HT")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournitures', to='bibliotheque.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Fourniture',
                'verbose_name_plural': 'Fournitures',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MainOeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom du type de main d'œuvre")),
                ('cout_horaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût horaire')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_oeuvre', to='bibliotheque.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': "Main d'œuvre",
                'verbose_name_plural': "Main d'œuvre",
                'ordering': ['nom'],
            },
        ),
    ]
