# Generated by Django 5.2.3 on 2025-06-24 13:56

import devis.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=50, unique=True, verbose_name="Numéro"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("accepted", "Accepté"),
                            ("rejected", "Refusé"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Nom du client"),
                ),
                (
                    "client_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du client"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom du projet",
                    ),
                ),
                (
                    "project_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Adresse du projet"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=devis.models.get_current_date,
                        verbose_name="Date d'émission",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "validity_period",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Durée de validité (jours)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conditions générales"
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TVA",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Créé par"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mis à jour par",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="tiers.tiers",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Produit"),
                            ("service", "Service"),
                            ("work", "Ouvrage"),
                            ("chapter", "Chapitre"),
                            ("section", "Section"),
                            ("discount", "Remise"),
                        ],
                        default="product",
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Unité"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "vat_rate",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("5.5", "5.5%"),
                            ("10", "10%"),
                            ("20", "20%"),
                        ],
                        default="20",
                        max_length=10,
                        verbose_name="Taux TVA",
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Marge (%)",
                    ),
                ),
                (
                    "total_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total HT",
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "work_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ID Ouvrage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="devis.quoteitem",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="devis.quote",
                        verbose_name="Devis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de devis",
                "verbose_name_plural": "Éléments de devis",
                "ordering": ["position"],
            },
        ),
    ]
