<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-06-20 15:36
=======
# Generated by Django 5.2.3 on 2025-06-23 09:19
>>>>>>> main

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet du devis')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyé', 'Envoyé'), ('accepté', 'Accepté'), ('refusé', 'Refusé'), ('annulé', 'Annulé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de devis')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validite', models.DateField(blank=True, null=True, verbose_name='Date de validité')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('conditions_paiement', models.TextField(blank=True, null=True, verbose_name='Conditions de paiement')),
                ('marge_globale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marge globale (%)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='tiers.tiers', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du lot')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='devis.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['devis', 'ordre', 'nom'],
                'unique_together': {('devis', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ouvrage', 'Ouvrage de la bibliothèque'), ('manuel', 'Ligne manuelle')], default='manuel', max_length=20, verbose_name='Type de ligne')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('debourse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Déboursé sec unitaire')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('ouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='bibliotheque.ouvrage', verbose_name='Ouvrage')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.lot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['lot', 'ordre'],
            },
        ),
    ]
