# Generated by Django 5.1.6 on 2025-06-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('acompte', 'Acompte'), ('solde', 'Solde'), ('avancement', 'Avancement')], default='solde', max_length=20, verbose_name='Type de facture')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee_partiellement', 'Payée partiellement'), ('payee', 'Payée')], default='brouillon', max_length=30, verbose_name='Statut')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('montant_payé', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Reste à payer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devis', models.OneToOneField(limit_choices_to={'statut': 'accepte'}, on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='devis.devis', verbose_name='Devis lié')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('sous_total_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total HT')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
        migrations.CreateModel(
            name='PaiementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(auto_now_add=True, verbose_name='Date de paiement')),
                ('moyen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Moyen de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement de facture',
                'verbose_name_plural': 'Paiements de facture',
            },
        ),
    ]
