# Generated by Django 5.2.3 on 2025-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiers",
            name="type",
            field=models.CharField(
                choices=[("entreprise", "Entreprise"), ("particulier", "Particulier")],
                default="entreprise",
                max_length=20,
            ),
        ),
    ]
