# Generated by Django 5.2.3 on 2025-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiers", "0002_alter_tiers_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresse",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="libelle",
            field=models.CharField(blank=True, max_length=100, verbose_name="Libellé"),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="rue",
            field=models.CharField(blank=True, max_length=255, verbose_name="Rue"),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="ville",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="nom",
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="prenom",
            field=models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
        ),
    ]
